@url = https://8080-tbsrick-07112024swcerto-wu9qszqb2zk.ws-us116.gitpod.io

GET {{url}}/plataformas

###
POST {{url}}/plataformas
Content-Type: application/json

{
    "nome" : "XBox"
}

###
DELETE {{url}}/plataformas/1

###
PUT {{url}}/plataformas/5
Content-Type: application/json

{
    "nome": "Alterado"
}